import IProxy from "../../../frame/pureMvc/interfaces/IProxy";
import Proxy from "../../../frame/pureMvc/patterns/proxy/Proxy";
import Grad from "../../lineGame/component/Grad";
import { GRADTYPE } from "../componnent/TankGrad";
import { TankGameVo } from "./vo/TankGameVo";

export default class TankGameProxy extends Proxy implements IProxy {
    static NAME = "TankGameProxy";
    /**
     * 被注册调用
     */
    public onRegister() {
        console.log("TankGameProxy被调用");
    }

    /**
     * 被删除调用
     */
    public onRemove() {
        console.log("TankGameProxy被删除");
    }

    public createMap() {
        let map = [
            [GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE],
            [GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE],
            [GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE],
            [GRADTYPE.BRICK, GRADTYPE.BRICK, GRADTYPE.BRICK, GRADTYPE.BRICK, GRADTYPE.BRICK, GRADTYPE.BRICK, GRADTYPE.BRICK, GRADTYPE.BRICK, GRADTYPE.BRICK, GRADTYPE.BRICK, GRADTYPE.BRICK, GRADTYPE.BRICK, GRADTYPE.BRICK],
            [GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE],
            [GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE],
            [GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE, GRADTYPE.NONE],

        ]


        let data = this.getData() as TankGameVo;
        data.mapArr = map;
    }


}